openapi: '3.1.1'
info:
  title: Food Bank Finder & Management API
  version: '1.0'
servers:
  - url: http://localhost:<port>/v1
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 1
        username:
          type: string
          minLength: 3
          maxLength: 20
        email:
          type: string
        
    FoodBank:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          minLength: 3
          maxLength: 75
          example: freeFoodBank
        unit_no:
          type: integer
        street:
          type: string
          minLength: 5
          maxLength: 50
          example: 555 Food St.
        city:
          type: string
          minLength: 2
          maxLength: 20
          example: Toronto
        locality:
          type: string
          minLength: 2
          maxLength: 20
          description: a province or state or locality or area
          example: Ontario
        country:
          type: string
          minLength: 2
          maxLength: 20
          example: Canada
        website:
          type: string
          minLength: 4
          example: www.freeFoodBank.org
        phone:
          type: integer
          description: validate to no more than 10 characters
          example: 5555555555
        fax:
          type: integer
          description: validate to no more than 10 characters
        charity_registration_no:
          type: integer
        postal_code:
          type: string
          minLength: 4
          maxLength: 6
        longitude:
          type: number
          format: decimal
          description: not part of MVP
        latitude:
          type: number
          format: decimal
          description: not part of MVP

    Category:
      type: object
      required:
      - id
      - name
      properties:
        id:
          type: integer
        name:
          type: string
      description: 'the food category'
    
    Hours:
      type: object
      properties:
        id:
          type: integer
          example: 1
        fb_id:
          type: integer
          example: 1
        weekday:
          type: integer
          example: 3
          minimum: 1
          maximum: 7
        opening_hr: 
          type: integer
          format: time
        closing_hr:
          type: integer
          format: time 
        temporarily_closed:
          type: boolean
          default: false 
  
    FoodInventory:
      type: object 
      properties:
        fb_id: 
          type: integer
        food_id:
          type: integer
        quantity:
          type: integer
          default: 0

    BoxInventory:
      type: object
      properties:
        fb_id:
          type: integer
        box_id:
          type: integer
        quantity:
          type: integer
          default: 0    
      
    Food:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
          minLength: 2
          maxLength: 30
        description:
          type: string
          maxLength: 100
        category:
          type: string
        box: 
          type: integer
        barcode:
          type: integer
          minLength: 1
          maxLength: 13
  
    Box:
      type: object
      required:
      - id
      - name
      - fb_id
      properties:
        id:
          type: integer
        name:
          type: string
          description: max length 35
        fb_id:
          type: integer
          minimum: 1
          description: the food bank id
      description: ''

    ErrorResponse:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          description: A machine-readable error code like 500
          enum:
            - INTERNAL_SERVER_ERROR # constant equal to 500
            - NOT_FOUND_ERROR # constant equal to 404
        message:
          type: string
          description: A human-readable message describing the error.
          example: "An unexpected internal server error occurred"

  responses:
    InternalServerError:
      description: An unexpected internal server error occurred.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            genericError:
              value:
                code: INTERNAL_SERVER_ERROR
                message: "An unexpected internal server error occurred"

paths:
  # the api documentation
  /:
    get:
      description: 'returns this yaml file'
      responses:
        '200':
          description: OK
          content:             
            application/yaml:
              schema:
                type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/responses/InternalServerError'
  # list of all registered food banks
  /fb:
    get:
      description: 'returns all food banks list'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FoodBank'
                example:
                  - id: 1
                    name: freeFoodBank
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/responses/InternalServerError'
  /category:
    get:
      description: 'returns a list of categories'
      responses:
        '200':
          description: OK
          content:             
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'        
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/responses/InternalServerError'
  /hours: 
    get:
      description: 'returns hours'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Hours'
  /food_inventory:
    get:
      description: 'returns a list of food inventories'  
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FoodInventory'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/responses/InternalServerError'   
  /box_inventory:
    get:
      description: "returns the list of box inventories"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BoxInventory'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/responses/InternalServerError'
  /food:
    get:
      description: "Returns the food list"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Food'

        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/responses/InternalServerError'
  /boxes:
    get:
      description: "returns the list of boxes"

